/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteJfaeiphfadArgs } from "./DeleteJfaeiphfadArgs";
import { JfaeiphfadFindManyArgs } from "./JfaeiphfadFindManyArgs";
import { JfaeiphfadFindUniqueArgs } from "./JfaeiphfadFindUniqueArgs";
import { Jfaeiphfad } from "./Jfaeiphfad";
import { JfaeiphfadService } from "../jfaeiphfad.service";

@graphql.Resolver(() => Jfaeiphfad)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class JfaeiphfadResolverBase {
  constructor(
    protected readonly service: JfaeiphfadService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Jfaeiphfad",
    action: "read",
    possession: "any",
  })
  async _jfaeiphfadsMeta(
    @graphql.Args() args: JfaeiphfadFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Jfaeiphfad])
  @nestAccessControl.UseRoles({
    resource: "Jfaeiphfad",
    action: "read",
    possession: "any",
  })
  async jfaeiphfads(
    @graphql.Args() args: JfaeiphfadFindManyArgs
  ): Promise<Jfaeiphfad[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Jfaeiphfad, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Jfaeiphfad",
    action: "read",
    possession: "own",
  })
  async jfaeiphfad(
    @graphql.Args() args: JfaeiphfadFindUniqueArgs
  ): Promise<Jfaeiphfad | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Jfaeiphfad)
  @nestAccessControl.UseRoles({
    resource: "Jfaeiphfad",
    action: "delete",
    possession: "any",
  })
  async deleteJfaeiphfad(
    @graphql.Args() args: DeleteJfaeiphfadArgs
  ): Promise<Jfaeiphfad | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
