/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteFsedgbbArgs } from "./DeleteFsedgbbArgs";
import { FsedgbbFindManyArgs } from "./FsedgbbFindManyArgs";
import { FsedgbbFindUniqueArgs } from "./FsedgbbFindUniqueArgs";
import { Fsedgbb } from "./Fsedgbb";
import { FsedgbbService } from "../fsedgbb.service";

@graphql.Resolver(() => Fsedgbb)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FsedgbbResolverBase {
  constructor(
    protected readonly service: FsedgbbService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Fsedgbb",
    action: "read",
    possession: "any",
  })
  async _fsedgbbsMeta(
    @graphql.Args() args: FsedgbbFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Fsedgbb])
  @nestAccessControl.UseRoles({
    resource: "Fsedgbb",
    action: "read",
    possession: "any",
  })
  async fsedgbbs(
    @graphql.Args() args: FsedgbbFindManyArgs
  ): Promise<Fsedgbb[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Fsedgbb, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Fsedgbb",
    action: "read",
    possession: "own",
  })
  async fsedgbb(
    @graphql.Args() args: FsedgbbFindUniqueArgs
  ): Promise<Fsedgbb | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Fsedgbb)
  @nestAccessControl.UseRoles({
    resource: "Fsedgbb",
    action: "delete",
    possession: "any",
  })
  async deleteFsedgbb(
    @graphql.Args() args: DeleteFsedgbbArgs
  ): Promise<Fsedgbb | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
