/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteRrrrArgs } from "./DeleteRrrrArgs";
import { RrrrFindManyArgs } from "./RrrrFindManyArgs";
import { RrrrFindUniqueArgs } from "./RrrrFindUniqueArgs";
import { Rrrr } from "./Rrrr";
import { RrrrService } from "../rrrr.service";

@graphql.Resolver(() => Rrrr)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class RrrrResolverBase {
  constructor(
    protected readonly service: RrrrService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Rrrr",
    action: "read",
    possession: "any",
  })
  async _rrrrsMeta(
    @graphql.Args() args: RrrrFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Rrrr])
  @nestAccessControl.UseRoles({
    resource: "Rrrr",
    action: "read",
    possession: "any",
  })
  async rrrrs(@graphql.Args() args: RrrrFindManyArgs): Promise<Rrrr[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Rrrr, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Rrrr",
    action: "read",
    possession: "own",
  })
  async rrrr(@graphql.Args() args: RrrrFindUniqueArgs): Promise<Rrrr | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Rrrr)
  @nestAccessControl.UseRoles({
    resource: "Rrrr",
    action: "delete",
    possession: "any",
  })
  async deleteRrrr(@graphql.Args() args: DeleteRrrrArgs): Promise<Rrrr | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
