/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteVsfefefeefsfeArgs } from "./DeleteVsfefefeefsfeArgs";
import { VsfefefeefsfeFindManyArgs } from "./VsfefefeefsfeFindManyArgs";
import { VsfefefeefsfeFindUniqueArgs } from "./VsfefefeefsfeFindUniqueArgs";
import { Vsfefefeefsfe } from "./Vsfefefeefsfe";
import { VsfefefeefsfeService } from "../vsfefefeefsfe.service";

@graphql.Resolver(() => Vsfefefeefsfe)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class VsfefefeefsfeResolverBase {
  constructor(
    protected readonly service: VsfefefeefsfeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Vsfefefeefsfe",
    action: "read",
    possession: "any",
  })
  async _vsfefefeefsfesMeta(
    @graphql.Args() args: VsfefefeefsfeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Vsfefefeefsfe])
  @nestAccessControl.UseRoles({
    resource: "Vsfefefeefsfe",
    action: "read",
    possession: "any",
  })
  async vsfefefeefsfes(
    @graphql.Args() args: VsfefefeefsfeFindManyArgs
  ): Promise<Vsfefefeefsfe[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Vsfefefeefsfe, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Vsfefefeefsfe",
    action: "read",
    possession: "own",
  })
  async vsfefefeefsfe(
    @graphql.Args() args: VsfefefeefsfeFindUniqueArgs
  ): Promise<Vsfefefeefsfe | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Vsfefefeefsfe)
  @nestAccessControl.UseRoles({
    resource: "Vsfefefeefsfe",
    action: "delete",
    possession: "any",
  })
  async deleteVsfefefeefsfe(
    @graphql.Args() args: DeleteVsfefefeefsfeArgs
  ): Promise<Vsfefefeefsfe | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
