/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteEeeeeArgs } from "./DeleteEeeeeArgs";
import { EeeeeFindManyArgs } from "./EeeeeFindManyArgs";
import { EeeeeFindUniqueArgs } from "./EeeeeFindUniqueArgs";
import { Eeeee } from "./Eeeee";
import { EeeeeService } from "../eeeee.service";

@graphql.Resolver(() => Eeeee)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class EeeeeResolverBase {
  constructor(
    protected readonly service: EeeeeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Eeeee",
    action: "read",
    possession: "any",
  })
  async _eeeeesMeta(
    @graphql.Args() args: EeeeeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Eeeee])
  @nestAccessControl.UseRoles({
    resource: "Eeeee",
    action: "read",
    possession: "any",
  })
  async eeeees(@graphql.Args() args: EeeeeFindManyArgs): Promise<Eeeee[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Eeeee, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Eeeee",
    action: "read",
    possession: "own",
  })
  async eeeee(
    @graphql.Args() args: EeeeeFindUniqueArgs
  ): Promise<Eeeee | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Eeeee)
  @nestAccessControl.UseRoles({
    resource: "Eeeee",
    action: "delete",
    possession: "any",
  })
  async deleteEeeee(
    @graphql.Args() args: DeleteEeeeeArgs
  ): Promise<Eeeee | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
