/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteTttttArgs } from "./DeleteTttttArgs";
import { TttttFindManyArgs } from "./TttttFindManyArgs";
import { TttttFindUniqueArgs } from "./TttttFindUniqueArgs";
import { Ttttt } from "./Ttttt";
import { TttttService } from "../ttttt.service";

@graphql.Resolver(() => Ttttt)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TttttResolverBase {
  constructor(
    protected readonly service: TttttService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Ttttt",
    action: "read",
    possession: "any",
  })
  async _tttttsMeta(
    @graphql.Args() args: TttttFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Ttttt])
  @nestAccessControl.UseRoles({
    resource: "Ttttt",
    action: "read",
    possession: "any",
  })
  async ttttts(@graphql.Args() args: TttttFindManyArgs): Promise<Ttttt[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Ttttt, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Ttttt",
    action: "read",
    possession: "own",
  })
  async ttttt(
    @graphql.Args() args: TttttFindUniqueArgs
  ): Promise<Ttttt | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ttttt)
  @nestAccessControl.UseRoles({
    resource: "Ttttt",
    action: "delete",
    possession: "any",
  })
  async deleteTtttt(
    @graphql.Args() args: DeleteTttttArgs
  ): Promise<Ttttt | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
